import { Routes } from '@angular/router';
import {HomePage} from '../pages/home/home-page';
import {NotFoundPage} from '../pages/not-found/not-found';

export const routes: Routes = [
  {path: "home", component: HomePage, title: "Angular UI components styled with Bootstrap"},
  {path: "components", loadComponent: () => import('../pages/components/components').then(m => m.ComponentsPage),
    children: [
      {path: "overview", loadComponent: () => import('../pages/components/overview/overview').then(m => m.OverviewPage)},
      {path: "alert", loadComponent: () => import('../pages/components/alert/alert').then(m => m.AlertPage)},
      {path: "autocomplete", loadComponent: () => import('../pages/components/autocomplete/autocomplete').then(m => m.AutocompletePage)},
      {path: "badge", loadComponent: () => import('../pages/components/badge/badge').then(m => m.BadgePage)},
      {path: "bottom-sheet", loadComponent: () => import('../pages/components/bottom-sheet/bottom-sheet').then(m => m.BottomSheetPage)},
      {path: "button", loadComponent: () => import('../pages/components/button/button').then(m => m.ButtonPage)},
      {path: "button-toggle", loadComponent: () => import('../pages/components/button-toggle/button-toggle').then(m => m.ButtonTogglePage)},
      {path: "card", loadComponent: () => import('../pages/components/card/card').then(m => m.CardPage)},
      {path: "checkbox", loadComponent: () => import('../pages/components/checkbox/checkbox').then(m => m.CheckboxPage)},
      {path: "chips", loadComponent: () => import('../pages/components/chips/chips').then(m => m.ChipsPage)},
      {path: "collapse", loadComponent: () => import('../pages/components/collapse/collapse').then(m => m.CollapsePage)},
      {path: "datepicker", loadComponent: () => import('../pages/components/datepicker/datepicker').then(m => m.DatepickerPage)},
      {path: "dialog", loadComponent: () => import('../pages/components/dialog/dialog').then(m => m.DialogPage)},
      {path: "divider", loadComponent: () => import('../pages/components/divider/divider').then(m => m.DividerPage)},
      {path: "expansion", loadComponent: () => import('../pages/components/expansion-panel/expansion-panel').then(m => m.ExpansionPanelPage)},
      {path: "form-field", loadComponent: () => import('../pages/components/form-field/form-field').then(m => m.FormFieldPage)},
      {path: "grid-list", loadComponent: () => import('../pages/components/grid-list/grid-list').then(m => m.GridListPage)},
      {path: "icon", loadComponent: () => import('../pages/components/icon/icon').then(m => m.IconPage)},
      {path: "input", loadComponent: () => import('../pages/components/input/input').then(m => m.InputPage)},
      {path: "list", loadComponent: () => import('../pages/components/list/list').then(m => m.ListPage)},
      {path: "menu", loadComponent: () => import('../pages/components/menu/menu').then(m => m.MenuPage)},
      {path: "paginator", loadComponent: () => import('../pages/components/paginator/paginator').then(m => m.PaginatorPage)},
      {path: "progress-bar", loadComponent: () => import('../pages/components/progress-bar/progress-bar').then(m => m.ProgressBarPage)},
      {path: "progress-spinner", loadComponent: () => import('../pages/components/progress-spinner/progress-spinner').then(m => m.ProgressSpinnerPage)},
      {path: "radio", loadComponent: () => import('../pages/components/radio-button/radio-button').then(m => m.RadioButtonPage)},
      {path: "select", loadComponent: () => import('../pages/components/select/select').then(m => m.SelectPage)},
      {path: "sidenav", loadComponent: () => import('../pages/components/sidenav/sidenav').then(m => m.SidenavPage)},
      {path: "slide-toggle", loadComponent: () => import('../pages/components/slide-toggle/slide-toggle').then(m => m.SlideTogglePage)},
      {path: "slider", loadComponent: () => import('../pages/components/slider/slider').then(m => m.SliderPage)},
      {path: "snack-bar", loadComponent: () => import('../pages/components/snack-bar/snack-bar').then(m => m.SnackBarPage)},
      {path: "sort", loadComponent: () => import('../pages/components/sort/sort').then(m => m.SortPage)},
      {path: "stepper", loadComponent: () => import('../pages/components/stepper/stepper').then(m => m.StepperPage)},
      {path: "table", loadComponent: () => import('../pages/components/table/table').then(m => m.TablePage)},
      {path: "tabs", loadComponent: () => import('../pages/components/tabs/tabs').then(m => m.TabsPage)},
      {path: "timepicker", loadComponent: () => import('../pages/components/timepicker/timepicker').then(m => m.TimepickerPage)},
      {path: "toolbar", loadComponent: () => import('../pages/components/toolbar/toolbar').then(m => m.ToolbarPage)},
      {path: "tooltip", loadComponent: () => import('../pages/components/tooltip/tooltip').then(m => m.TooltipPage)},
      {path: "tree", loadComponent: () => import('../pages/components/tree/tree').then(m => m.TreePage)},
    ]},
  {path: "pro-components", loadComponent: () => import('../pages/pro-components/overview/overview').then(m => m.OverviewProPage)},
  {path: "", redirectTo: "home", pathMatch: "full"},
  {path: "**", component: NotFoundPage},
];
